import type { Metadata } from "next";

import { Navbar } from "../components/Navbar";
import { Footer } from "../components/Footer";

import "./globals.css";

export const metadata: Metadata = {
  title: "Fresco Foods",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="sticky top-0 z-10">
          <Navbar />
        </header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
